name: Compile and test

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mcs HsluvTest/HsluvConverterTest.cs HsluvTest/MiniJSON.cs Hsluv/Hsluv.cs -resource:HsluvTest/snapshot-rev4.json,JsonSnapshotRev4 -main:HsluvTest.HsluvConverterTest
      - run: mono ./HsluvTest/HsluvConverterTest.exe
